// ivg.scad -- Autococker Inner Velocity Governor (IVG / IVA)
// Thread: 3/4"-16 UNF, 60-deg ISO/UN profile.  Units: mm.
//
//   Major dia  D = 0.750"  = 19.05 mm
//   Pitch      P = 1/16"    = 1.5875 mm  (16 TPI)
//   Right-hand thread, driven by an allen key from the back.
//
// Self-contained: no libraries. The thread is generated by the linear_extrude
// "cam-profile" method -- a solid 2D blob whose outer radius varies with angle
// so that twisting it reproduces a true 60-deg V-thread (flank slope = tan30).
//
// ---- PRINTING NOTE ------------------------------------------------------
//   thread_clearance is a RADIAL relief of the FLANKS (pitch diameter). It
//   never touches the crest, so the major diameter is ALWAYS exactly 19.05 --
//   that is a hard requirement of this part, so do not "clear" it by shrinking
//   the OD. Set thread_clearance = 0 for exact nominal 3/4-16 geometry;
//   ~0.06 mm is a sane starting point for an FDM male thread into metal.
// -------------------------------------------------------------------------

// Shared interface dims (D, P, thread_clearance, length, bore_d, scallop_wall/
// floor, drive_wall + derived rroot, rcrest, cavity_r, cavity_depth,
// drive_hole_d, drive_circle_r). The driver tool includes the same file.
include <lib/ivg_shared.scad>

/* [Thread] */
right_hand      = true;

/* [Body] */
front_chamfer   = 1.0;      // lead-in chamfer at the tip (valve side)
back_chamfer    = 0.6;      // chamfer at the drive end

/* [Bore] */
bore_fn         = 180;      // facets on the center bore

/* [Scallop] */
scallop         = true;     // hollow out the interior into a thin-walled cup
scallop_open    = "back";   // open end face: "back" (drive) or "front" (tip)
scallop_fn      = 120;      // facets on the scallop cylinder

/* [O-ring] */
o_ring          = true;     // An oring partially engages the threads to prevent backout
o_ring_diameter = 15;       // O-ring slot is 19/32"
o_ring_height   = 2;        // O-ring height/gap is 5/64"

/* [Drive holes] */
drive_holes     = true;     // four holes in the floor (90 deg apart) for a pin tool
drive_hole_fn   = 60;       // facets on each drive hole

/* [Side slots] */
slots           = true;     // six through-wall windows down the side
slot_count      = 6;        // number of slots, evenly spaced around
slot_w          = 5.5;      // slot width (tangential) = round-cutter diameter
slot_z_bottom   = 7;      // slot floor, measured up from the base (z=0)
slot_open_top   = true;     // true: open through the top of the threads
                            // false: rounded cap just below the top
slot_fn         = 48;       // facets on each slot cutter

/* [Quality] */
seg_per_turn    = 32;       // helix slices per revolution
cam_step        = 3;        // deg between thread cam points (smaller = smoother)
env_fn          = 96;       // facets for the round envelope

// A_ROOT / A_FLANK / A_CREST (angular widths of one period) come from
// lib/ivg_shared.scad, where thread_clearance is folded into the two flats.

function cam_r(a) =
    let(t = ((a % 360) + 360) % 360)
      t <  A_ROOT                        ? rroot :
      t <  A_ROOT + A_FLANK              ? rroot  + (t - A_ROOT)/A_FLANK*(rcrest - rroot) :
      t <  A_ROOT + A_FLANK + A_CREST    ? rcrest :
                                           rcrest - (t - A_ROOT - A_FLANK - A_CREST)/A_FLANK*(rcrest - rroot);

// One profile segment, sampled at <= cam_step and INCLUDING its start angle.
function cam_arc(s, e) =
    let(n = max(1, ceil((e - s) / cam_step)))
    [ for (i = [0 : n-1]) let(a = s + (e - s) * i / n)
        [ cam_r(a)*cos(a), cam_r(a)*sin(a) ] ];

// Solid 2D cam whose radius sweeps root->crest->root once around. Sampled per
// segment rather than on a blind fixed grid, so exact vertices always land on
// the four profile breakpoints -- in particular on both ends of the crest flat,
// which is what pins the outside diameter at D once the flats stop being
// multiples of cam_step.
module thread_cam() {
    a1 = A_ROOT; a2 = a1 + A_FLANK; a3 = a2 + A_CREST;
    polygon(concat(cam_arc(0, a1), cam_arc(a1, a2),
                   cam_arc(a2, a3), cam_arc(a3, 360)));
}

// Full-length threaded blank (flat ends, ragged crest at the very tips).
module threaded_blank() {
    turns = length / P;
    linear_extrude(height = length,
                   twist  = (right_hand ? -1 : 1) * 360 * turns,
                   slices = max(2, ceil(turns * seg_per_turn)),
                   convexity = 10)
        thread_cam();
}

// Round envelope with 45-deg chamfers top & bottom -- intersected with the
// blank to give clean chamfered thread lead-ins at both ends.
//
// rotate_extrude inscribes its polygon in the circle, so a straight side at
// D/2 actually sits at D/2*cos(180/env_fn) between vertices and would shave
// ~0.01 mm off the crest all the way round. Circumscribe instead: the FLATS
// then land on D/2 and the envelope can never cut inside the major diameter.
module envelope() {
    er = (D/2) / cos(180 / env_fn);
    rotate_extrude($fn = env_fn)
        polygon([
            [0,                  0],
            [er - front_chamfer, 0],
            [er,                 front_chamfer],
            [er,                 length - back_chamfer],
            [er - back_chamfer,  length],
            [0,                  length],
        ]);
}

// Six through-wall side windows. Each is a rounded-end axial slot cut radially
// from the axis out past the thread crest (so it pierces the wall into the
// hollow cavity). Made by hulling two radial cylinders of diameter `slot_w`,
// which gives semicircular top/bottom caps -- the look of a `slot_w` round-nose
// cutter. Spans from `slot_z_bottom` up to (or through) the top of the threads.
module side_slots() {
    r      = slot_w / 2;
    zb     = slot_z_bottom + r;                 // center of the rounded bottom cap
    zt     = slot_open_top ? length + 1         // run full-width out through the top
                           : length - r;        // rounded cap apex at the top
    radial = D/2 + 2;                            // punch from axis out past the crest
    for (i = [0 : slot_count - 1])
        rotate([0, 0, i * 360 / slot_count])
            hull() {
                translate([0, 0, zb]) rotate([0, 90, 0])
                    cylinder(h = radial, r = r, $fn = slot_fn);
                translate([0, 0, zt]) rotate([0, 90, 0])
                    cylinder(h = radial, r = r, $fn = slot_fn);
            }
}

// ===================== the part =====================
module ivg() {
    difference() {
        intersection() {
            threaded_blank();
            envelope();
        }
        // through-bore, full length
        translate([0, 0, -0.1])
            cylinder(h = length + 0.2, d = bore_d, $fn = bore_fn);

        // scalloped cavity: hollow the interior leaving `scallop_wall` at the
        // thread root (the thinnest wall), open through one end face, floor on
        // the other. Wall is thicker (+thread depth) at the crests.
        if (scallop) {
            sc_h  = cavity_depth + 0.1;
            sc_z0 = (scallop_open == "front") ? -0.1 : scallop_floor;
            translate([0, 0, sc_z0])
                cylinder(h = sc_h, r = cavity_r, $fn = scallop_fn);
        }

        // four drive holes through the floor, 90 deg apart, for a pin-spanner
        // tool. Placed on drive_circle_r within the cavity so the tool reaches
        // them straight down from the open end (see lib/ivg_shared.scad for
        // sizing). The driver carries only three pins -- its side slot omits the
        // fourth -- so it can enter at any of two clockings but always drives.
        if (drive_holes) {
            hz0 = (scallop_open == "front") ? length - scallop_floor - 0.1 : -0.1;
            for (a = [0, 90, 180, 270])
                rotate([0, 0, a])
                    translate([drive_circle_r, 0, hz0])
                        cylinder(h = scallop_floor / 2, d = drive_hole_d,
                                 $fn = drive_hole_fn);
        }

        // six through-wall side windows, top of threads down to slot_z_bottom
        if (slots) side_slots();
        
        // O-ring groove. The outer cutter must clear the crest by a margin: at
        // d = D on default $fn (~30 facets) its flats sit at 9.4728, INSIDE the
        // 9.525 crest, and it leaves ~30 scalloped slivers of thread in the
        // groove. Oversize it -- nothing of the part lives out there anyway.
        if(o_ring) {
            translate([0, 0, 3.4]) {
                difference() {
                    cylinder(h = o_ring_height, d = D + 2, center = true, $fn = env_fn);
                    cylinder(h = o_ring_height, d = o_ring_diameter, center = true, $fn = bore_fn);
                }
            }
        }
    }
}

echo(str("IVG  major=", 2*rcrest, " (nominal ", D, ")  pitch=", pitch_d,
         "  minor=", 2*rroot, "  cavity_d=", cavity_d, "  floor=", scallop_floor));
echo(str("FORM  flank=", 2*atan((A_FLANK/360*P) / (rcrest-rroot)), " deg incl",
         "  root flat=", A_ROOT/360*P, "  crest flat=", A_CREST/360*P,
         "  (clearance ", thread_clearance, " -> ", flank_relief, " deg relief)"));
echo(str("DRIVE  4x holes  d=", drive_hole_d, "  on R=", drive_circle_r,
         "  90deg apart (pitch ", 2*drive_circle_r, " across)"));
echo(str("SLOTS  ", slots ? slot_count : 0, "x  w=", slot_w,
         "  z=", slot_z_bottom, "..", slot_open_top ? length : length - slot_w/2,
         "  open_top=", slot_open_top));

ivg();
